### ISSUE TITLE
Not entirely sure whether it's PEX Acting up

### ISSUE THREAD

**Issue by Munkeywaxx** [TekkitCommando/PromotionEssentials#1]
Hey, so I'm configuring PromoEssentials for a few people I know and keep coming across errors.

As the title states, it could be A PEX Thing, so I will send a link to this post over there on the PEX Repo:

So, I have about 2.7k Lines written in a PEX Perms.yml with inheritances/ladders yadda yadda but the "Default" group can't access any PromoESS Signs. 

_Note_ Sorry for the shitty formatting, I've not learned much MarkDown.

With the /pex toggle debug enabled it states that:
22.11 22:24:35 [Server] INFO User Munkeywaxx checked for permission 'promotionessentials.sign.use.pioneer', no match found (CACHE MISS)

I Am in the world where the permissions are enabled. Signs have been created correctly in said world.

  groups:
    Guest:
    worlds:
      PVP:
        permissions:
        - insertPermNodeHere
      MainWorld:
        permissions:
        - promotionessentials.rank.buy.pioneer

Honestly, I have no clue whether it's PromoESS Or the way I have PEX Setup, just in need of guidance currently.

**Comment by Munkeywaxx** [comment]
Ignore this, TOTALLY forgot about worlds in permissions being case-sensitive.

**Comment by ethsmith** [comment]
Lol ok @Munkeywaxx
